language: python

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - pip install -r requirements-test.txt
    - pip install coveralls
    # It's necessary to install the project to create the update-conf.py bin.
    # It's used by the 'test_script.py' module.
    - python setup.py develop

script:
    - make check
    # It's necessary to run tests as 'sudo'. 'sudo' is used by the
    # 'test_sudo_config.py' module.
    # Setting the PATH is also necessary for 'sudo make' finding the binary.
    - sudo PATH=$PATH make test-with-coverage

after_success: coveralls
