# tests

version: 0.2

env:
  secrets-manager:
    COVERALLS_REPO_TOKEN: "update-conf-py-DO-NOT-USE/codebuild:COVERALLS_REPO_TOKEN"

batch:
  build-list:
    - identifier: python3_7
      env:
        image: aws/codebuild/standard:5.0
        variables:
          PYTHON_VERSION: 3.7
    - identifier: python3_8
      env:
        image: aws/codebuild/standard:5.0
        variables:
          PYTHON_VERSION: 3.8
    - identifier: python3_9
      env:
        image: aws/codebuild/standard:5.0
        variables:
          PYTHON_VERSION: 3.9
    - identifier: python3_10
      env:
        image: aws/codebuild/standard:6.0
        variables:
          PYTHON_VERSION: "3.10"

phases:
  install:
    runtime-versions:
      python: ${PYTHON_VERSION}
  pre_build:
    commands:
      # Add the pyenv global binary dir to PATH, as this isn't done by default
      # on CodeBuild.
      - export PATH=$(pyenv prefix)/bin:$PATH
      - python -m pip install -r requirements-test.txt
      - python -m pip install coveralls
      # Install `update-conf.py` script to make it available to the
      # 'test_script.py' test module.
      - python setup.py develop
  build:
    commands:
      - make check
      - make test-with-coverage
      - coverage lcov
      - coverage xml
  post_build:
    commands:
      # Set correct env vars expected by coveralls
      # See: https://docs.coveralls.io/supported-ci-services
      - env
      - CI_NAME=codebuild CI_BRANCH=${CODEBUILD_SOURCE_VERSION} coveralls

reports:
  coverage:
    files:
      - coverage.xml
    file-format: COBERTURAXML
