# build-and-publish

version: 0.2

env:
  secrets-manager:
    TEST_PYPI_API_TOKEN: "update-conf-py-DO-NOT-USE/codebuild:TEST_PYPI_API_TOKEN"
    PYPI_API_TOKEN: "update-conf-py-DO-NOT-USE/codebuild:PYPI_API_TOKEN"

phases:
  install:
    runtime-versions:
      python: "3.10"
  pre_build:
    commands:
      # Add the pyenv global binary dir to PATH, as this isn't done by default
      # on CodeBuild.
      - export PATH=$(pyenv prefix)/bin:$PATH
      - python -m pip install -r requirements-dev.txt
      - aws codeartifact login --tool twine --domain test --repository pypi

  build:
    commands:
      - python setup.py sdist bdist_wheel
      - make check-build
  post_build:
    commands:
      - twine upload --repository-url https://test.pypi.org/legacy/ -u __token__ -p $TEST_PYPI_API_TOKEN dist/*
      - twine upload -u __token__ -p $PYPI_API_TOKEN dist/*
      - twine upload -r codeartifact dist/*
